import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className=" h-full flex items-center justify-center  bg-[radial-gradient(ellipse_at_top,var(--tw-gradient-stops))] from-rose-400 to-rose-600  ">
      <div className={inter.className}>{children}</div>
    </main>
  );
}
